version: '2'

services:
  dev:
    image: node:9.6.1
    command: bash
    working_dir: /app
    user: $NODE_USER
    volumes:
      - .:/app
  index:
    image: node:9.6.1
    command: node index.js
    working_dir: /app
    user: $NODE_USER
    volumes:
      - .:/app
